// Generated from Final for Adwait 1.csv and Book1.csv
const scheduleData = [
  // Masterclasses (24-30 Jan)
  {
    "title": "Creating a Sense of Community with Intention",
    "description": "A masterclass by Laurie Frank",
    "date": "2026-01-24",
    "startTime": "10:00",
    "endTime": "17:00",
    "location": "Bengaluru",
    "track": "Masterclass",
    "speakers": ["Laurie Frank"],
    "capacity": 80,
    "duration": 420,
    "category": "Conference"
  },
  {
    "title": "Remarkable Program Design",
    "description": "A masterclass by Mark Collard",
    "date": "2026-01-24",
    "startTime": "10:00",
    "endTime": "17:00",
    "location": "Bengaluru",
    "track": "Masterclass",
    "speakers": ["Mark Collard"],
    "capacity": 80,
    "duration": 420,
    "category": "Conference"
  },
  {
    "title": "Thinking Experientially",
    "description": "A masterclass by Laurie Frank",
    "date": "2026-01-25",
    "startTime": "10:00",
    "endTime": "17:00",
    "location": "Bengaluru",
    "track": "Masterclass",
    "speakers": ["Laurie Frank"],
    "capacity": 80,
    "duration": 420,
    "category": "Conference"
  },
  {
    "title": "Critical Facilitation Skills",
    "description": "A masterclass by Mark Collard",
    "date": "2026-01-25",
    "startTime": "10:00",
    "endTime": "17:00",
    "location": "Bengaluru",
    "track": "Masterclass",
    "speakers": ["Mark Collard"],
    "capacity": 80,
    "duration": 420,
    "category": "Conference"
  },
  {
    "title": "Creating a Sense of Community with Intention",
    "description": "A masterclass by Laurie Frank",
    "date": "2026-01-29",
    "startTime": "10:00",
    "endTime": "17:00",
    "location": "Pune",
    "track": "Masterclass",
    "speakers": ["Laurie Frank"],
    "capacity": 80,
    "duration": 420,
    "category": "Conference"
  },
  {
    "title": "Remarkable Program Design",
    "description": "A masterclass by Mark Collard",
    "date": "2026-01-29",
    "startTime": "10:00",
    "endTime": "17:00",
    "location": "Pune",
    "track": "Masterclass",
    "speakers": ["Mark Collard"],
    "capacity": 80,
    "duration": 420,
    "category": "Conference"
  },
  {
    "title": "Thinking Experientially",
    "description": "A masterclass by Laurie Frank",
    "date": "2026-01-30",
    "startTime": "10:00",
    "endTime": "17:00",
    "location": "Pune",
    "track": "Masterclass",
    "speakers": ["Laurie Frank"],
    "capacity": 80,
    "duration": 420,
    "category": "Conference"
  },
  {
    "title": "Critical Facilitation Skills",
    "description": "A masterclass by Mark Collard",
    "date": "2026-01-30",
    "startTime": "10:00",
    "endTime": "17:00",
    "location": "Pune",
    "track": "Masterclass",
    "speakers": ["Mark Collard"],
    "capacity": 80,
    "duration": 420,
    "category": "Conference"
  },
  
  // 31st Jan Sessions
  {
    "title": "MISSION CRITICAL: An Intent-Based Leadership Simulation",
    "description": "Interactive leadership simulation focusing on intent-based leadership and decision-making under pressure.",
    "date": "2026-01-31",
    "startTime": "10:30",
    "endTime": "13:15",
    "location": "Pune",
    "track": "Experience Based T&D",
    "speakers": ["Arvind Khinvesra", "Ameena Bukhari"],
    "capacity": 80,
    "duration": 165,
    "category": "Conference"
  },
  {
    "title": "Sport as a Medium for Social Justice",
    "description": "Can play be a pathway to justice? This immersive session invites participants to explore what justice means to them and how the energy and spirit of sport can inspire equity, inclusion, and collective empowerment.",
    "date": "2026-01-31",
    "startTime": "10:30",
    "endTime": "13:15",
    "location": "Pune",
    "track": "Inclusive Practices",
    "speakers": ["Shubhomoy Bhaduri", "Shikha Bohra"],
    "capacity": 80,
    "duration": 165,
    "category": "Conference"
  },
  {
    "title": "A workshop with Sarabjit Singh Wallia",
    "description": "Experience-based workshop session led by Sarabjit Singh Wallia.",
    "date": "2026-01-31",
    "startTime": "10:30",
    "endTime": "12:00",
    "location": "Pune",
    "track": "Experience Based T&D",
    "speakers": ["Sarabjit Singh Wallia"],
    "capacity": 80,
    "duration": 90,
    "category": "Conference"
  },
  {
    "title": "Designing Experiences That Stick: Tools for Connection, Reflection, and Growth",
    "description": "Practical tools to design engaging experiences that deepen connection, reflection, and growth for learners.",
    "date": "2026-01-31",
    "startTime": "10:30",
    "endTime": "12:00",
    "location": "Pune",
    "track": "Experience Based T&D",
    "speakers": ["Sakshi Rawat"],
    "capacity": 80,
    "duration": 90,
    "category": "Conference"
  },
  {
    "title": "A social emotional learning workshop delivered through play!",
    "description": "This workshop is about exploring the opportunities of SEL in any story. Take any classroom subject like history or geography and add more colour to it with reflective SEL questions. Learn how to come up with simple questions that fall in the categories of the 5 pillars of SEL: self-awareness, self-management, relationship management, responsible decision-making, and social awareness.",
    "date": "2026-01-31",
    "startTime": "14:15",
    "endTime": "17:30",
    "location": "Pune",
    "track": "K-12",
    "speakers": ["Chetan Vohra"],
    "capacity": 80,
    "duration": 195,
    "category": "Conference"
  },
  {
    "title": "The Art of Learning to Learn",
    "description": "This workshop, The Art of Learning to Learn, invites participants to explore how learning truly happens—within the mind, body, and experience of the learner. It is designed for educators, facilitators, coaches, and anyone curious about deepening their understanding of how humans make meaning, retain knowledge, and transform through awareness.",
    "date": "2026-01-31",
    "startTime": "12:15",
    "endTime": "13:15",
    "location": "Pune",
    "track": "K-12",
    "speakers": ["Divya Arathi Madiazhagan"],
    "capacity": 80,
    "duration": 60,
    "category": "Conference"
  },
  {
    "title": "Beyond Psychological Safety: Integrating Somatics and the Polyvagal Lens in Experiential Facilitation",
    "description": "Beyond Psychological Safety explores how embodied awareness can transform learning spaces into containers of genuine safety and depth. This 3-hour experiential session invites facilitators, educators, and coaches to discover how the nervous system shapes engagement, reflection, and connection.",
    "date": "2026-01-31",
    "startTime": "14:15",
    "endTime": "15:45",
    "location": "Pune",
    "track": "Experience Based T&D",
    "speakers": ["Diyanat Ali"],
    "capacity": 80,
    "duration": 90,
    "category": "Conference"
  },
  {
    "title": "Setting the Benchmark: Quality Delivery & Price Standardisation in Experiential Education in India",
    "description": "The workshop aims to bring together key stakeholders to collaboratively define standards for delivery quality and pricing in the rapidly evolving experiential education sector.",
    "date": "2026-01-31",
    "startTime": "14:15",
    "endTime": "15:45",
    "location": "Pune",
    "track": "Experience Based T&D",
    "speakers": ["Junaid Hussain"],
    "capacity": 80,
    "duration": 90,
    "category": "Conference"
  },
  {
    "title": "Differentiated Pedagogies Through the Lens of Puppetry and Voice Modulation",
    "description": "Inclusive education thrives on inclusive tools. This session positions puppetry and voice modulation as powerful pedagogical strategies for differentiated learning.",
    "date": "2026-01-31",
    "startTime": "14:15",
    "endTime": "15:45",
    "location": "Pune",
    "track": "Experience Based T&D",
    "speakers": ["Rinti Sengupta"],
    "capacity": 80,
    "duration": 90,
    "category": "Conference"
  },
  {
    "title": "Unboring History: Discovering the Stories Things Tell",
    "description": "In the age of AI, when facts are instantly accessible, memorizing historical data loses meaning. This session invites educators to move beyond content delivery toward cultivating historical thinking—the ability to look deeply, feel deeply, and think deeply.",
    "date": "2026-01-31",
    "startTime": "16:00",
    "endTime": "17:30",
    "location": "Pune",
    "track": "K-12",
    "speakers": ["Prachi Dalal"],
    "capacity": 80,
    "duration": 90,
    "category": "Conference"
  },
  {
    "title": "Where Quiet Grows",
    "description": "Where Quiet Grows is an immersive, nature-based creative workshop designed to explore the intersection of art, ecology, and wellbeing. It invites participants to experience nature as collaborator, guide, and healer through multi-sensory engagement and creative expression.",
    "date": "2026-01-31",
    "startTime": "10:30",
    "endTime": "12:00",
    "location": "Pune",
    "track": "Nature Based Practices",
    "speakers": ["Ritu Dua"],
    "capacity": 80,
    "duration": 90,
    "category": "Conference"
  },
  {
    "title": "Interactive Art, Theatre and Play as Experiential Pathways to Creating Safe Group Spaces for Sexuality Education",
    "description": "To make sexuality accessible, safe, contextual and experiential, this workshop uses Expressive Art Installations, Theatre of the Oppressed tools, Play for Peace games and Dance Movement Therapy practices.",
    "date": "2026-01-31",
    "startTime": "12:15",
    "endTime": "13:15",
    "location": "Pune",
    "track": "Inclusive Practices",
    "speakers": ["Simran Sanganeria"],
    "capacity": 80,
    "duration": 60,
    "category": "Conference"
  },
  {
    "title": "Play as Resistance: Reclaiming Joy, Justice, and Connection",
    "description": "Play as Resistance is an experiential learning workshop that invites participants to explore how playful facilitation can restore compassion, foster social justice, and build meaningful human connections across divides.",
    "date": "2026-01-31",
    "startTime": "14:15",
    "endTime": "17:30",
    "location": "Pune",
    "track": "Inclusive Practices",
    "speakers": ["Sinthuja Shanmuganathan", "Swati Bhatt", "Agyatmitra"],
    "capacity": 80,
    "duration": 195,
    "category": "Conference"
  },
  {
    "title": "Embodied Pedagogies: How Ritual and Belief Shape Learning Spaces",
    "description": "This 90-minute session invites participants into an exploration of how belief systems, rituals, and ancestral wisdom can reshape the way we understand and facilitate learning.",
    "date": "2026-01-31",
    "startTime": "16:00",
    "endTime": "17:30",
    "location": "Pune",
    "track": "Nature Based Practices",
    "speakers": ["Srishti Malpath"],
    "capacity": 80,
    "duration": 90,
    "category": "Conference"
  },
  {
    "title": "From Turbulence to Tranquility: Navigating Learning and Life with SEL",
    "description": "This workshop reimagines Social and Emotional Learning (SEL) as every child's entitlement—a compass that equips learners to face the future with confidence and courage.",
    "date": "2026-01-31",
    "startTime": "12:15",
    "endTime": "13:15",
    "location": "Pune",
    "track": "K-12",
    "speakers": ["Sumita Gowdety"],
    "capacity": 80,
    "duration": 60,
    "category": "Conference"
  },
  {
    "title": "Designing the Experience: The Art and Architecture of Transformative Learning",
    "description": "In experiential education, meaningful learning does not occur by chance, it is designed. This presentation explores Experience Design as the intentional architecture behind powerful experience-based training.",
    "date": "2026-01-31",
    "startTime": "12:15",
    "endTime": "13:15",
    "location": "Pune",
    "track": "Experience Based T&D",
    "speakers": ["Usha Krishnan"],
    "capacity": 80,
    "duration": 60,
    "category": "Conference"
  },
  {
    "title": "Let the learning happen - Do not teach!",
    "description": "Have you struggled to 'teach' a concept or topic to your audience? This session is about 'not to teach - Let them learn'! You will experience ways to make the learning process interesting and engaging.",
    "date": "2026-01-31",
    "startTime": "10:30",
    "endTime": "12:00",
    "location": "Pune",
    "track": "Experience Based T&D",
    "speakers": ["Vivek Yatnalkar"],
    "capacity": 80,
    "duration": 90,
    "category": "Conference"
  },
  {
    "title": "The Synthetic Friend: When AI Listens but No One Else Does",
    "description": "The Synthetic Friend invites educators to explore a quiet emotional revolution happening in classrooms as students begin to replace real connection with artificial companionship.",
    "date": "2026-01-31",
    "startTime": "10:30",
    "endTime": "12:00",
    "location": "Pune",
    "track": "K-12",
    "speakers": ["Racy Shukla"],
    "capacity": 80,
    "duration": 90,
    "category": "Conference"
  },
  {
    "title": "Exploring The ObVerse - The other side of coin!",
    "description": "ObVerse is a deep dive into understanding - Why some of the Experiential Learning and Facilitation sessions land well while others don't.",
    "date": "2026-01-31",
    "startTime": "16:00",
    "endTime": "17:30",
    "location": "Pune",
    "track": "Experience Based T&D",
    "speakers": ["Yateen Gharat"],
    "capacity": 80,
    "duration": 90,
    "category": "Conference"
  },
  {
    "title": "The Discipline of Subtraction",
    "description": "When trying to create effective learning experiences, facilitators often make things too complicated. This session presents a simple design method: The Discipline of Subtraction.",
    "date": "2026-01-31",
    "startTime": "12:15",
    "endTime": "13:15",
    "location": "Pune",
    "track": "Experience Based T&D",
    "speakers": ["Nidhi Mittal"],
    "capacity": 80,
    "duration": 60,
    "category": "Conference"
  },

  // 1st Feb Sessions
  {
    "title": "Immersive Sound Meditation Session",
    "description": "A guided sound meditation to ground and reset through immersive auditory experience.",
    "date": "2026-02-01",
    "startTime": "09:30",
    "endTime": "10:30",
    "location": "Pune",
    "track": "Nature Based Practices",
    "speakers": ["Gayatri Singh"],
    "capacity": 80,
    "duration": 60,
    "category": "Conference"
  },
  {
    "title": "From Fibre to Freedom",
    "description": "From Fibre to Freedom is a hybrid workshop from the valleys of Ladakh that threads together the act of making and the act of understanding. Through the lens of spinning, the session invites participants to trace the journey of fibre from raw Pashmina and Yak wool.",
    "date": "2026-02-01",
    "startTime": "10:45",
    "endTime": "12:15",
    "location": "Pune",
    "track": "Experience Based T&D",
    "speakers": ["Anchita Kaul", "Tsewang Yangzes"],
    "capacity": 80,
    "duration": 90,
    "category": "Conference"
  },
  {
    "title": "A Workshop with Vinay Sirsi",
    "description": "Interactive workshop facilitated by Vinay Sirsi.",
    "date": "2026-02-01",
    "startTime": "10:45",
    "endTime": "12:15",
    "location": "Pune",
    "track": "Experience Based T&D",
    "speakers": ["Vinay Sirsi"],
    "capacity": 80,
    "duration": 90,
    "category": "Conference"
  },
  {
    "title": "NLP for Experiential Educators",
    "description": "This workshop invites experiential learning practitioners to discover how Neuro-Linguistic Programming can serve as a multidimensional tool to deepen the impact of the experiences they already curate.",
    "date": "2026-02-01",
    "startTime": "09:00",
    "endTime": "12:15",
    "location": "Pune",
    "track": "Experience Based T&D",
    "speakers": ["Anup Talwar"],
    "capacity": 80,
    "duration": 195,
    "category": "Conference"
  },
  {
    "title": "Seeing Experiential Education in classroom through a Montessori Lens",
    "description": "This experiential session invites educators and facilitators to step into the Montessori approach. The workshop offers an experiential session based on how to use Montessori principles to re-design and scaffold learning spaces.",
    "date": "2026-02-01",
    "startTime": "13:15",
    "endTime": "14:45",
    "location": "Pune",
    "track": "K-12",
    "speakers": ["Ashima Sheth"],
    "capacity": 80,
    "duration": 90,
    "category": "Conference"
  },
  {
    "title": "Feel, Play, Grow",
    "description": "Step into a space where learning feels alive, where curiosity, play, and reflection meet. We explore how experiential methodology can help us build more connected classrooms and relationships.",
    "date": "2026-02-01",
    "startTime": "15:00",
    "endTime": "16:30",
    "location": "Pune",
    "track": "K-12",
    "speakers": ["Hemali Gandhi"],
    "capacity": 80,
    "duration": 90,
    "category": "Conference"
  },
  {
    "title": "Cultivating Well-being Through the Practice of Mandala of Systems Awareness",
    "description": "This workshop will explore the Mandala for Systems Awareness, a framework to help us reflect and understand the complexity and interconnectedness of life.",
    "date": "2026-02-01",
    "startTime": "09:00",
    "endTime": "12:15",
    "location": "Pune",
    "track": "K-12",
    "speakers": ["Jasmin Jasin", "Sahala Harap"],
    "capacity": 80,
    "duration": 195,
    "category": "Conference"
  },
  {
    "title": "Atlas of Emotions – EMO Lab",
    "description": "In this 3-hour experiential session, we'll explore the Atlas of Emotions — a powerful framework to understand the rich landscape of our emotional experiences.",
    "date": "2026-02-01",
    "startTime": "13:15",
    "endTime": "16:30",
    "location": "Pune",
    "track": "Experience Based T&D",
    "speakers": ["Kavitha Talreja", "Roopashree Surana"],
    "capacity": 80,
    "duration": 195,
    "category": "Conference"
  },
  {
    "title": "Forest of Stories: Exploring Identity through Storying and Re-storying",
    "description": "In Narrative Therapy, stories hold a significant value in a person's life. Through movement, nature and art-based activities, this workshop will explore the formation of stories of our lives.",
    "date": "2026-02-01",
    "startTime": "10:45",
    "endTime": "12:15",
    "location": "Pune",
    "track": "Nature Based Practices",
    "speakers": ["Mukta Joshi"],
    "capacity": 80,
    "duration": 90,
    "category": "Conference"
  },
  {
    "title": "SHAKTI Warriors- Warriors in Action",
    "description": "This interactive workshop introduces SHAKTI Warriors, a pioneering program that brings Social and Emotional Development (SED) to life through gamification, storytelling, and play.",
    "date": "2026-02-01",
    "startTime": "09:00",
    "endTime": "10:30",
    "location": "Pune",
    "track": "K-12",
    "speakers": ["Natasha Nayar", "Lane Jabaay"],
    "capacity": 80,
    "duration": 90,
    "category": "Conference"
  },
  {
    "title": "The body knows your power: Embodied learning to nurture learners' agency",
    "description": "This 90-minute session invites participants to rediscover agency through their own bodies and relationships, using improvisational theatre and guided movement.",
    "date": "2026-02-01",
    "startTime": "13:15",
    "endTime": "14:45",
    "location": "Pune",
    "track": "Experience Based T&D",
    "speakers": ["Niken Rasarati", "Tuuli Utriainen"],
    "capacity": 80,
    "duration": 90,
    "category": "Conference"
  },
  {
    "title": "Experiential Education and Social Justice: Co-Creating Frameworks for Practice",
    "description": "This three-hour interactive workshop explores the intersections of experiential education and social justice, inviting educators into a space of reflection, dialogue, and co-creation.",
    "date": "2026-02-01",
    "startTime": "13:15",
    "endTime": "16:30",
    "location": "Pune",
    "track": "K-12",
    "speakers": ["Pratyay Malakar"],
    "capacity": 80,
    "duration": 195,
    "category": "Conference"
  },
  {
    "title": "Mindful Conflict Management: Building Collaborative Culture at the Workplace",
    "description": "In this workshop, participants will explore a chosen topic using Psychodrama and Sociodrama, experiential methods developed by Dr. J. L. Moreno.",
    "date": "2026-02-01",
    "startTime": "09:00",
    "endTime": "12:15",
    "location": "Pune",
    "track": "Experience Based T&D",
    "speakers": ["Rashmi Datt"],
    "capacity": 80,
    "duration": 195,
    "category": "Conference"
  },
  {
    "title": "Beyond the Binary: Reimagining Safety and Inclusion for Trans and Gender-Diverse People in Outdoor and Experiential Learning",
    "description": "Trans* and gender-diverse individuals often face barriers to inclusion. This workshop invites educators to reimagine what safety and belonging can mean.",
    "date": "2026-02-01",
    "startTime": "09:00",
    "endTime": "10:30",
    "location": "Pune",
    "track": "Inclusive Practices",
    "speakers": ["Riju Banerjee"],
    "capacity": 80,
    "duration": 90,
    "category": "Conference"
  },
  {
    "title": "Panels of Possibility: Learning Comic Writing as an EE Tool",
    "description": "Comics engage Head, Heart and Hand beautifully. Used judiciously, comics can be like colourful little superheroes - simplifying complex ideas and enabling powerful reflection.",
    "date": "2026-02-01",
    "startTime": "15:00",
    "endTime": "16:30",
    "location": "Pune",
    "track": "Experience Based T&D",
    "speakers": ["Tanushree Banerji"],
    "capacity": 80,
    "duration": 90,
    "category": "Conference"
  },
  {
    "title": "What can Leaders learn from School Principals",
    "description": "The workshop will explore the critical role Program Leaders play in the success of a program unit. Participants will explore the three board frameworks (People, Program, Operations).",
    "date": "2026-02-01",
    "startTime": "13:15",
    "endTime": "14:45",
    "location": "Pune",
    "track": "K-12",
    "speakers": ["Somsuvra Chatterjee", "Caroline Nagar"],
    "capacity": 80,
    "duration": 90,
    "category": "Conference"
  },
  {
    "title": "Embodied Listening': The Art of Receiving",
    "description": "In the 'Embodied Listening' workshop, we shall experience how the act and presence of deep listening actually feels like. A framework called 'Open Window Listening' will be introduced.",
    "date": "2026-02-01",
    "startTime": "13:15",
    "endTime": "14:15",
    "location": "Pune",
    "track": "Experience Based T&D",
    "speakers": ["Nidhi Chavan"],
    "capacity": 80,
    "duration": 60,
    "category": "Conference"
  },
  {
    "title": "Connecting with the Self 2 through Self 1: Tapping into the unconscious through conscious triggers",
    "description": "In high pressure moments, how does one cut through the mind's chatter and perform to their best of abilities? In this session we put into application the theory of Self 1 and Self 2.",
    "date": "2026-02-01",
    "startTime": "09:00",
    "endTime": "10:30",
    "location": "Pune",
    "track": "Experience Based T&D",
    "speakers": ["Aaryan Sen"],
    "capacity": 80,
    "duration": 90,
    "category": "Conference"
  },
  {
    "title": "The Facilitator as Instrument: Exploring Embodied Presence in Experiential Learning",
    "description": "What if the real method is who we are while doing it? Embodied facilitation recognizes that our body, breath, and nervous system constantly communicate.",
    "date": "2026-02-01",
    "startTime": "15:00",
    "endTime": "16:00",
    "location": "Pune",
    "track": "Experience Based T&D",
    "speakers": ["Zuhail Babu P"],
    "capacity": 80,
    "duration": 60,
    "category": "Conference"
  },
  {
    "title": "Contextual Sensitisers",
    "description": "Hands-on practice to design contextual sensitisers that align facilitation with participant realities and session goals.",
    "date": "2026-02-01",
    "startTime": "15:00",
    "endTime": "16:30",
    "location": "Pune",
    "track": "Experience Based T&D",
    "speakers": ["Rutesh Panditrao"],
    "capacity": 80,
    "duration": 90,
    "category": "Conference"
  }
]

export { scheduleData }
